name: deploy to environments

on:
  workflow_dispatch:

jobs:
  sync_copilot:
    uses: NHSDigital/eps-common-workflows/.github/workflows/pr_title_check.yml@copilot
    permissions:
      contents: write
      pull-requests: write
